name: stock_ml_train
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - ipykernel # to enable jupyter notebook for local development
  - python=3.11
  - pip
  - pip:
      - -r requirements.txt
      - -e .
