name: model training pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch: # entry point for inference to trigger a retrain

  # Allows external webhook trigger
  repository_dispatch:
    types:
      - webhook

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4 # gives github actions access to your repository

      - name: Set up Python
        uses: actions/setup-python@v5 # lets you install a specific python version
        with:
          python-version: "3.12"
          cache: "pip" # caching pip dependencies

      - name: Install Python packages
        run: |
          pip install --upgrade pip 
          pip install -r requirements.txt 
          pip install -e .

      - name: Test with pytest
        run: pytest tests/ --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html

      - name: Train machine learning model
        env:
          TF_ENABLE_ONEDNN_OPTS: "0" # turn off one DNN custom operations
          TF_CPP_MIN_LOG_LEVEL: "3" # needed to suppress out of rand warnings
          HF_TOKEN: ${{secrets.HF_TOKEN}}
          HOPSWORKS_KEY: ${{secrets.HOPSWORKS_KEY}}
          NEPTUNE_TOKEN: ${{secrets.NEPTUNE_TOKEN}}
          ENV_NAME: prod
        run: python main.py
