name: model training pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - uses: iterative/setup-cml@v2

      - name: Install Packages
        run: |
          pip install --upgrade pip 
          pip install -r requirements.txt 
          pip install -e .

      - name: Test with pytest
        run: pytest tests/ --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html

      - name: Train
        run: python main.py

      - name: Upload training logs
        uses: actions/upload-artifact@v3
        with:
          name: training-logs
          path: logs/

      - name: Download training logs
        uses: actions/download-artifact@v3
        with:
          name: training-logs

      - name: Start TensorBoard
        run: |
          tensorboard --logdir=logs/
