name: model training pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # gives github actions access to your repository
      - uses: iterative/setup-cml@v2 # to display model metrics

      - name: Install Packages
        run: |
          pip install --upgrade pip 
          pip install -r requirements.txt 
          pip install -e .

      - name: Test with pytest
        run: pytest tests/ --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html

      - name: Train
        run: python main.py
        env:
          HF_TOKEN: $${{secrets.HF_TOKEN}}
